"""Project-wide constants kept in one module to avoid magic numbers."""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[2]
DATA_DIR = BASE_DIR / "data"
LEVEL_DIR = DATA_DIR / "levels"
SAVE_DIR = DATA_DIR / "saves"
SAVE_FILE = SAVE_DIR / "save.json"
SCORES_FILE = SAVE_DIR / "scores.json"
SOUND_DIR = BASE_DIR / "wav"
MUSIC_DIR = BASE_DIR / "music"
SHOT_SOUND_FILE = SOUND_DIR / "hit.wav"
BUFF_SOUND_FILE = SOUND_DIR / "buffs.wav"
KEY_SOUND_FILE = SOUND_DIR / "key.wav"
HEALTH_SOUND_FILE = SOUND_DIR / "take_healh.wav"
MONSTER_DEATH_SOUND_FILE = SOUND_DIR / "monster_death.wav"
MENU_MUSIC_FILE = MUSIC_DIR / "menu.wav"
LEVEL_ONE_MUSIC_FILE = MUSIC_DIR / "mus01.wav"
LEVEL_TWO_MUSIC_FILE = MUSIC_DIR / "mus02.wav"
ENDLESS_MUSIC_FILE = MUSIC_DIR / "mus03.wav"

SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768
FPS = 60
MIN_ACCEPTABLE_FPS = 30

TILE_SIZE = 48
MAP_WIDTH = 25
MAP_HEIGHT = 18
HUD_HEIGHT = 54

PLAYER_SIZE = 34
PLAYER_SPEED = 250
PLAYER_MAX_HP = 100
PLAYER_AMMO = 12
PLAYER_RESERVE_AMMO = 60
PLAYER_RELOAD_SECONDS = 0.9
PLAYER_SHOOT_COOLDOWN = 0.18
PLAYER_DEFAULT_NAME = "Player"
PLAYER_NAME_MAX_LENGTH = 16
PLAYER_INVULNERABILITY_SECONDS = 10.0
PLAYER_DAMAGE_INVULNERABILITY_SECONDS = 0.5

BULLET_SIZE = 8
BULLET_SPEED = 720
BULLET_DAMAGE = 34
BULLET_LIFETIME = 1.4

ZOMBIE_SIZE = 34
ZOMBIE_SPEED = 110
ZOMBIE_HP = 68
ZOMBIE_DAMAGE = 12
ZOMBIE_ATTACK_COOLDOWN = 0.55
ZOMBIE_REPATH_SECONDS = 0.35
NORMAL_ZOMBIE_SCORE = 30
RED_ZOMBIE_SCORE = 50
BLUE_ZOMBIE_SCORE = 100
RED_ZOMBIE_HP_MULTIPLIER = 2
BLUE_ZOMBIE_HP_MULTIPLIER = 5
RED_ZOMBIE_SPAWN_CHANCE = 0.30
BLUE_ZOMBIE_SPAWN_CHANCE = 0.10

KEY_SIZE = 24
MEDKIT_SIZE = 26
MEDKIT_HEAL = 25
MEDKIT_DROP_CHANCE = 0.05
INVULNERABILITY_ORB_SIZE = 24
INVULNERABILITY_ORB_DROP_CHANCE = 0.05
PORTAL_SIZE = 52
WALL_THICKNESS = 6
TOP_SCORES_LIMIT = 5
WAVE_NEXT_TRIGGER_RATIO = 0.30
WAVE_MIN_NEXT_TRIGGER_KILLS = 3
LEVEL_ONE_WAVES = (5, 15, 25)
LEVEL_TWO_WAVES = (10, 30, 40)
ENDLESS_FIRST_WAVE_SIZE = 15
ENDLESS_WAVE_INCREMENT = 3

MENU_STATE = "menu"
PLAYING_STATE = "playing"
PAUSE_STATE = "pause"
SCORES_STATE = "scores"
GAME_OVER_STATE = "game_over"
VICTORY_STATE = "victory"

LEVEL_ONE_ID = 1
LEVEL_TWO_ID = 2
ENDLESS_LEVEL_ID = 3

WHITE = (238, 241, 245)
BLACK = (10, 12, 14)
GRAY = (72, 78, 84)
DARK_GRAY = (35, 39, 45)
GREEN = (81, 179, 99)
RED = (213, 72, 71)
BLUE = (67, 139, 224)
YELLOW = (235, 196, 73)
CYAN = (91, 201, 202)
PURPLE = (151, 105, 222)
ORANGE = (223, 134, 67)
